const routes = ["home", "url-detector", "email-header", "attachment-analyzer", "about"];
const routeButtons = document.querySelectorAll("[data-route]");
const views = document.querySelectorAll("[data-view]");
const suspiciousTlds = ["zip", "mov", "top", "xyz", "tk", "ml", "ga", "cf", "gq", "buzz", "click"];
const suspiciousWords = ["login", "verify", "update", "secure", "account", "bank", "password", "wallet", "free", "bonus", "urgent", "limited", "support", "claim"];
const knownBrands = ["paypal", "google", "microsoft", "apple", "amazon", "netflix", "facebook", "instagram", "whatsapp", "bank"];
const dangerousExtensions = ["exe", "scr", "bat", "cmd", "com", "js", "jse", "vbs", "vbe", "ps1", "msi", "jar", "hta", "lnk"];
const macroExtensions = ["docm", "xlsm", "pptm"];
const archiveExtensions = ["zip", "rar", "7z", "iso", "img"];
let selectedAttachment = null;
routeButtons.forEach((button) => button.addEventListener("click", () => navigateTo(button.dataset.route)));
window.addEventListener("DOMContentLoaded", () => { const initialRoute = location.hash.replace("#", ""); navigateTo(routes.includes(initialRoute) ? initialRoute : "home", false); });
window.addEventListener("hashchange", () => { const route = location.hash.replace("#", ""); if (routes.includes(route)) navigateTo(route, false); });
document.getElementById("scan-url").addEventListener("click", analyzeUrl);
document.getElementById("scan-header").addEventListener("click", analyzeHeader);
document.getElementById("scan-attachment").addEventListener("click", analyzeAttachment);
const attachmentInput = document.getElementById("attachment-input");
const dropZone = document.querySelector(".drop-zone");
attachmentInput.addEventListener("change", () => setSelectedAttachment(attachmentInput.files[0]));
["dragenter", "dragover"].forEach((eventName) => { dropZone.addEventListener(eventName, (event) => { event.preventDefault(); dropZone.classList.add("dragging"); }); });
["dragleave", "drop"].forEach((eventName) => { dropZone.addEventListener(eventName, (event) => { event.preventDefault(); dropZone.classList.remove("dragging"); }); });
dropZone.addEventListener("drop", (event) => setSelectedAttachment(event.dataTransfer.files[0]));
function navigateTo(route, updateHash = true) { views.forEach((view) => view.classList.toggle("active", view.dataset.view === route)); document.querySelectorAll(".nav-link").forEach((button) => button.classList.toggle("active", button.dataset.route === route)); if (updateHash) history.pushState(null, "", route === "home" ? location.pathname : "#" + route); window.scrollTo({ top: 0, behavior: "smooth" }); }
function analyzeUrl() { const input = document.getElementById("url-input").value.trim(); const findings = []; let score = 0; if (!input) { renderResult("url", "--", "Awaiting input", "neutral", ["Enter a URL in the sidebar, then run analysis."]); return; } let parsed; try { parsed = new URL(input.includes("://") ? input : "https://" + input); } catch { renderResult("url", 95, "Invalid or highly suspicious", "danger", ["The entered value is not a valid URL."]); return; } const host = parsed.hostname.toLowerCase(); const path = parsed.pathname.toLowerCase(); const full = parsed.href.toLowerCase(); const labels = host.split("."); const tld = labels.at(-1) || ""; if (parsed.protocol !== "https:") { score += 18; findings.push("URL does not use HTTPS, so data may be exposed in transit."); } if (/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) { score += 22; findings.push("The link uses a raw IP address instead of a readable domain."); } if (input.length > 95) { score += 12; findings.push("The URL is unusually long, a common hiding technique in phishing links."); } if (labels.length > 4) { score += 14; findings.push("The domain has many subdomains, which can be used to imitate trusted sites."); } if (suspiciousTlds.includes(tld)) { score += 12; findings.push("The ." + tld + " domain extension is often abused in low-trust campaigns."); } const keywordHits = suspiciousWords.filter((word) => full.includes(word)); if (keywordHits.length) { score += Math.min(22, keywordHits.length * 5); findings.push("Suspicious urgency or credential words found: " + keywordHits.slice(0, 5).join(", ") + "."); } const brandHits = knownBrands.filter((brand) => host.includes(brand)); if (brandHits.length && !brandHits.some((brand) => host === brand + ".com" || host.endsWith("." + brand + ".com"))) { score += 16; findings.push("Domain appears to reference a known brand without using its official domain."); } if (host.includes("-") || path.includes("@")) { score += 8; findings.push("The URL contains characters often used to make links look more legitimate than they are."); } if (!findings.length) findings.push("No major phishing pattern was detected from visible URL structure."); const finalScore = Math.min(100, score); renderResult("url", finalScore, verdictForRisk(finalScore), classForRisk(finalScore), findings); }
function analyzeHeader() { const header = document.getElementById("header-input").value.trim(); const analystMode = document.getElementById("analyst-mode").checked; const lower = header.toLowerCase(); const findings = []; let trust = 45; if (!header) { renderResult("header", "--", "Awaiting input", "neutral", ["Paste raw email headers in the sidebar, then run analysis."]); return; } const from = getHeaderValue(header, "from"); const replyTo = getHeaderValue(header, "reply-to"); const returnPath = getHeaderValue(header, "return-path"); if (lower.includes("spf=pass")) { trust += 16; findings.push("SPF passed, meaning the sending server is authorized by the sender domain."); } else if (lower.includes("spf=fail") || lower.includes("spf=softfail")) { trust -= 18; findings.push("SPF failed or soft-failed, which weakens sender authenticity."); } else findings.push("SPF result was not found in the pasted header."); if (lower.includes("dkim=pass")) { trust += 16; findings.push("DKIM passed, so the message has a valid cryptographic signature."); } else if (lower.includes("dkim=fail")) { trust -= 18; findings.push("DKIM failed, which may indicate spoofing or message tampering."); } else findings.push("DKIM result was not found in the pasted header."); if (lower.includes("dmarc=pass")) { trust += 16; findings.push("DMARC passed, aligning authentication with the sender domain policy."); } else if (lower.includes("dmarc=fail")) { trust -= 22; findings.push("DMARC failed, a strong warning sign for spoofed email."); } else findings.push("DMARC result was not found in the pasted header."); if ((from && replyTo && domainFrom(from) !== domainFrom(replyTo)) || (from && returnPath && domainFrom(from) !== domainFrom(returnPath))) { trust -= 15; findings.push("Sender, reply-to, or return-path domains do not match."); } const receivedCount = (lower.match(/^received:/gm) || []).length; if (receivedCount > 0) { findings.push(receivedCount + " mail server hop" + (receivedCount > 1 ? "s" : "") + " detected in the delivery path."); trust += Math.min(7, receivedCount); } else { trust -= 8; findings.push("No Received chain was found, so delivery path visibility is limited."); } if (analystMode) findings.push("Analyst mode: From=" + (from || "missing") + ", Reply-To=" + (replyTo || "missing") + ", Return-Path=" + (returnPath || "missing") + "."); const finalScore = clamp(trust, 0, 100); const verdict = finalScore >= 75 ? "Likely authentic" : finalScore >= 45 ? "Needs review" : "High spoofing risk"; const className = finalScore >= 75 ? "safe" : finalScore >= 45 ? "warn" : "danger"; renderResult("header", finalScore, verdict, className, findings); }
function setSelectedAttachment(file) { selectedAttachment = file || null; const summary = document.getElementById("file-summary"); if (!selectedAttachment) { summary.textContent = "No file selected."; renderResult("attachment", "--", "Awaiting input", "neutral", ["Drop or choose a file in the sidebar, then run analysis."]); return; } summary.textContent = selectedAttachment.name + " | " + formatBytes(selectedAttachment.size) + " | " + (selectedAttachment.type || "unknown type"); }
function analyzeAttachment() { if (!selectedAttachment) { renderResult("attachment", "--", "Awaiting input", "neutral", ["Drop or choose a file in the sidebar, then run analysis."]); return; } const fileName = selectedAttachment.name; const lowerName = fileName.toLowerCase(); const parts = lowerName.split("."); const extension = parts.length > 1 ? parts.at(-1) : ""; const findings = ["Selected file: " + fileName + " (" + formatBytes(selectedAttachment.size) + ")."]; let score = 12; if (!extension) { score += 18; findings.push("File has no visible extension, which makes its real type harder to verify."); } if (dangerousExtensions.includes(extension)) { score += 42; findings.push("High-risk executable or script extension detected: ." + extension + "."); } if (macroExtensions.includes(extension)) { score += 32; findings.push("Macro-enabled Office file detected: ." + extension + "."); } if (archiveExtensions.includes(extension)) { score += 18; findings.push("Archive or disk image extension detected: ." + extension + ". Inspect contents before opening."); } if (parts.length > 2 && dangerousExtensions.includes(extension)) { score += 20; findings.push("Double-extension pattern detected, often used to disguise executable files."); } if (/(invoice|payment|urgent|scan|document|kyc|password|verify)/i.test(fileName)) { score += 10; findings.push("Filename contains social-engineering words commonly used in malicious attachments."); } if (selectedAttachment.size > 50 * 1024 * 1024) { score += 12; findings.push("File is larger than the recommended 50 MB inspection limit."); } if (selectedAttachment.type) findings.push("Browser-reported MIME type: " + selectedAttachment.type + "."); else findings.push("Browser did not report a MIME type for this file."); if (score <= 20) findings.push("No major attachment risk pattern was detected from metadata."); const finalScore = clamp(score, 0, 100); const verdict = finalScore >= 70 ? "High attachment risk" : finalScore >= 35 ? "Needs sandbox review" : "Low visible risk"; const className = finalScore >= 70 ? "danger" : finalScore >= 35 ? "warn" : "safe"; renderResult("attachment", finalScore, verdict, className, findings); }
function renderResult(prefix, score, verdict, className, findings) { document.getElementById(prefix + "-score").textContent = score === "--" ? "--" : score + "%"; const verdictNode = document.getElementById(prefix + "-verdict"); verdictNode.textContent = verdict; verdictNode.className = "verdict " + className; document.getElementById(prefix + "-findings").innerHTML = findings.map((item) => "<li>" + escapeHtml(item) + "</li>").join(""); }
function verdictForRisk(score) { if (score >= 70) return "High phishing risk"; if (score >= 35) return "Needs review"; return "Low visible risk"; }
function classForRisk(score) { if (score >= 70) return "danger"; if (score >= 35) return "warn"; return "safe"; }
function getHeaderValue(header, key) { const regex = new RegExp("^" + key + ":\s*(.+)$", "im"); const match = header.match(regex); return match ? match[1].trim() : ""; }
function domainFrom(value) { const emailMatch = value.match(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/i); return emailMatch ? emailMatch[1].toLowerCase().replace(/[>)]$/, "").trim() : value.toLowerCase(); }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
function formatBytes(bytes) { if (bytes === 0) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const index = Math.floor(Math.log(bytes) / Math.log(1024)); return (bytes / Math.pow(1024, index)).toFixed(index === 0 ? 0 : 1) + " " + units[index]; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" })[char] || char); }
